## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [22]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [23]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [47]:
from sklearn.model_selection import train_test_split, KFold

X1 = X[:40]
y1 = y[:40]
X0 = X[40:]
y0 = y[40:]

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=10, random_state=0) #train:test = 30:10
X0_train, X0_test, y0_train, y0_test = train_test_split(X0, y0, test_size=10, random_state=0) #train:test = 150:10

In [54]:
x_train = np.vstack((X1_train,X0_train))
y_train = np.hstack((y1_train,y0_train))

x_test = np.vstack((X1_test,X0_test))
y_train = np.hstack((y1_test,y0_test))

In [57]:
x_test

array([[110, 111, 112, 113, 114],
       [100, 101, 102, 103, 104],
       [125, 126, 127, 128, 129],
       [ 20,  21,  22,  23,  24],
       [ 50,  51,  52,  53,  54],
       [ 75,  76,  77,  78,  79],
       [140, 141, 142, 143, 144],
       [ 55,  56,  57,  58,  59],
       [ 90,  91,  92,  93,  94],
       [145, 146, 147, 148, 149],
       [750, 751, 752, 753, 754],
       [760, 761, 762, 763, 764],
       [915, 916, 917, 918, 919],
       [235, 236, 237, 238, 239],
       [420, 421, 422, 423, 424],
       [705, 706, 707, 708, 709],
       [810, 811, 812, 813, 814],
       [530, 531, 532, 533, 534],
       [625, 626, 627, 628, 629],
       [630, 631, 632, 633, 634]])

In [58]:
y_train

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])